### PR TITLE
update to the latest dev release (1.22.0 12.0 dev)

### PR DESCRIPTION
**Pull request by devoncarew**
- update to the latest dev release (1.22.0 12.0 dev) - done as two commits for easier review

This brings in a lot of new cupertino icons.

### CODE REVIEW

**Review by DanTup — COMMENTED** [review]
Screenshot 2020-09-17 at 18 12 15

😄

LGTM!

**Comment by devoncarew** [comment]
> LGTM!

Thanks! Can you click the approve button? This repo needs an explicit approval to merge.

**Review by DanTup — APPROVED** [review]

**Comment by DanTup** [comment]
Ugh sorry, I thought I specifically clicked Approve but apparently not!

**Comment by DanTup** [comment]
@devoncarew while updating these in VS Code, I just noticed that many of these new icons are the same (incorrect) image:

Screenshot 2020-09-21 at 09 45 33

I think it would be better not to include them (not only for size, but so editors can handle missing images by not showing them if they'd prefer, rather than a placeholder) - though I'm not sure if they should actually be available?

**Comment by DanTup** [comment]
I'm also now suspicious about some of the others too - there's no preview on the Flutter site to compare this against, but I'm not sure if these ones are intended to be numbers?

Screenshot 2020-09-21 at 09 47 39

They're not all bad though, there are a lot that are definitely correct.

**Comment by devoncarew** [comment]
Is this an issue with our generator? With the source content? How they're intended to look?

I have a PR to bring the latest into IntelliJ but will hold off until this is resolved.

**Comment by DanTup** [comment]
I haven't done any digging yet (I secretly hoped you'd know what it was 😄). I'll take a look shortly and see what's going on.

**Comment by DanTup** [comment]
Figured it out - we need to upgrade to the cupertino_icons v1.0.0 package in the icon generator. PR on its way.

**Comment by devoncarew** [comment]
> Figured it out - we need to upgrade to the cupertino_icons v1.0.0 package in the icon generator. PR on its way.

Ah - great catch! I wonder how it was possible for these to get out of sync? The framework was referencing codepoints that only existed in the newer version of the package?

**Comment by DanTup** [comment]
Yeah, I think so. There are comments on the icons that say we need to use at least this version of the package (added in https://github.com/flutter/flutter/pull/65083), so I think it's expected behaviour.

**Pull request merged**
