### PR TITLE
Update to cupertino icons to v1.0.0 for icon_generator

### PR DESCRIPTION
**Pull request by DanTup**
The new icons added in https://github.com/flutter/flutter/pull/65083 required v1.0.0 of the cupertino_icons package to work.

The first commit updates the package version, the second commits all the generated icons.

As well as fixing all the broken icons, there are some slight changes in the existing icons too - I don't know if these are flip-flopping when we're generating them (I think you had the same), or just an update and won't happen again. Maybe worth you trying to generate using current dev to see if you get the same.

### CODE REVIEW

**Comment by DanTup** [comment]
I am wondering about the alignment though.. A lot of them seem to have space at the top and not at the bottom. I'm not sure if this is intended?

Screenshot 2020-09-21 at 17 36 27

**Comment by devoncarew** [comment]
We're displaying the icons here: https://github.com/flutter/tools_metadata/blob/master/tool/icon_generator/lib/main.dart#L88 - I assume the padding is inherent in the codepoint / font glyph itself?

**Review by devoncarew — APPROVED** [review]

**Comment by DanTup** [comment]
Yeah, I think so - if I render them with a border in a real Flutter app the alignment matches what we're generating here. So if they're not right, it may be the package/font that's wrong. @xster - is this correct?

```dart
Container(
  decoration: BoxDecoration(border: Border.all(color: Colors.red)),
  child: Icon(CupertinoIcons.refresh, size: 50),
)
```

Screenshot 2020-09-21 at 17 43 08

**Comment by xster** [comment]
Thanks for pointing it out. I might have messed up the fontforge autowidth usages.

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/66285

**Pull request merged**
