### PR TITLE
Allow manually check up-to-date

### PR DESCRIPTION
**Pull request by AlexV525**
The up-to-date check hasn't been run successfully for a long time. Some resources are outdated. https://github.com/flutter/tools_metadata/actions/workflows/check_up_to_date.yaml
The PR enables the manually run ability to check in order to find out causes.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by godofredoc** [comment]
Action workflows are not visible from development workflows. Please consider moving this check to LUCI

**Comment by godofredoc** [comment]
> Action workflows are not visible from development workflows. Please consider moving this check to LUCI

Please ignore my comment, I see this is on tools_metadata.

**Comment by AlexV525** [comment]
cc @devoncarew @DanTup

**Review by DanTup — APPROVED** [review]
LGTM

**Pull request merged**
