### PR TITLE
Update using current Flutter beta

### PR DESCRIPTION
**Pull request by DanTup**
@devoncarew @stevemessick this is generated using the current beta version of Flutter and adds new icons (and removes some) from recent changes like https://github.com/flutter/flutter/pull/111092.

GitHub doesn't do well with large PRs like this, so I committed the changes in several smaller commits (non-images, new images, updated images, removed images) so it may be easier to check the changes on [the Commits tab](https://github.com/flutter/tools_metadata/pull/34/commits).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- N/A I listed at least one issue that this PR fixes in the description above.
- N/A I updated/added relevant documentation (doc comments with `///`).
- N/A I added new tests to check the change I am making, or this PR is [test-exempt].
- N/A All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by devoncarew — APPROVED** [review]

**Comment by devoncarew** [comment]
lgtm! thanks

It looks like this moved us form flutter 3.1 to 3.7-beta. Perhaps we should have a check here - running ~weekly? - that confirms that we've re-generated recently. I.e., have generated for the current flutter stable.

**Comment by DanTup** [comment]
> confirms that we've re-generated recently. I.e., have generated for the current flutter stable.

If we check against stable, we'd start failing if we update before stable releases (which I think we should, to ensure IDEs shipping these are updated before stable releases). We could check against `beta`, although that might trigger more often than we'd like (eg. if icons are updated soon after a stable release and we want to hold off updating here until the (probable) last beta before a stable).

That said, updating on each beta where there are changes probably isn't terrible. It's fairly quick to do, and may even lead to slightly smaller PRs that will be easier to load in GH. Let me know what you think - I don't think it'd be difficult to set the bot up.

**Comment by devoncarew** [comment]
I was thinking of a check to make sure we at least support the last stable; that would then remind us ~once a release to update. I think we could structure the check so that its possible to update (to a beta) before a stable is out.

But really any check is better than none here - if you'd prefer checking against beta (making sure we update ~monthly) - sgtm.

**Comment by DanTup** [comment]
I think if we check against stable, the bot would always fail "too late" (after stable ships and the editors may have broken images, which some lead time to fix).

That said, it also occurs to me that updating early has the inverse issue... these changes removed some images (`whatsapp`) which means if an IDE ships these changes _before_ the next stable, they may break those images for stable users. I plan to ship these in VS Code around the same time as the next stable release, but that isn't always the case.

I feel like maybe the least-bad option is tracking beta, and making it the editors responsibilities to try and take these changes and ship them as close to the stable release as possible. WDYT?

(hopefully over time this becomes less of an issue if we can move more of this into the analysis server)

**Comment by devoncarew** [comment]
> I feel like maybe the least-bad option is tracking beta, and making it the editors responsibilities to try and take these changes and ship them as close to the stable release as possible. WDYT?

Sounds reasonable to me.

Another way to approach this would be to have the info versioned w/ the flutter version - for IDEs to retrieve or calculate the correct metadata based on the flutter version in use locally. But that's probably overkill for the problem-space; the user wouldn't see analysis errors w/ version mismatches, just a few icons w/ missing or not up-to-date previews.

**Pull request merged**
